### ISSUE TITLE
The 'send' button for feedback has disappeared

### ISSUE THREAD

**Issue by GroovinChip** [snapfeed/snapfeed-sdk#13]
There is only a textfield, but no send button.

![image](https://user-images.githubusercontent.com/4250470/70843175-f4d7c680-1dfb-11ea-9688-92eba01ed4ec.png)

**Comment by TheJulianJES** [comment]
You need to type at least five characters into the text field, before the send button appears.

**Comment by GroovinChip** [comment]
Perhaps an indication of that would be good for users? Like a minimum character counter or something

**Comment by flschweiger** [comment]
That's good feedback @GroovinChip 👍 Currently working on a re-design of the whole platform, which will hopefully make things more clear 😃
