### ISSUE TITLE
Update README to provide link for wiredash

### ISSUE THREAD

**Issue by TheJulianJES** [snapfeed/snapfeed-sdk#16]
It seems like https://github.com/wiredashio/wiredash-sdk // https://wiredash.io is the new project.
Although I knew about the name change, I didn't think it was already here.
Maybe it would be nice, if there was a link or something to the new project in the README.

**Comment by flschweiger** [comment]
Pssssst 🤫 You already found the new project which I didn't really announce yet - will do it in the upcoming days 😉

**Comment by TheJulianJES** [comment]
I guess it could be considered to add a link (or note) pointing to the new project now.

**Comment by flschweiger** [comment]
Thanks for the heads-up, just updated the readme 🙂
